export const projectNames = [
    "Catflix",
    "Dragon Bank",
    "Zombie Delivery",
    "Code Quest",
    "Snack Tracker",
    "Alien Marketplace",
    "Plant Doctor",
    "Space Weather",
    "Wizard Recipes",
    "Puppy Planner",
    "Time Capsule",
    "Ocean Cleanup",
    "Robot Races",
    "Book Nook",
    "Moon Journal",
    "Mystery Map",
    "Garden Guru",
    "Pixel Painter",
    "Treasure Hunt",
    "Music Mixer",
    "Cloud Kitchen",
    "Dino Museum",
    "Fitness Forest",
    "Weather Wizard",
    "Recipe Rocket",
    "Language Lantern",
    "Movie Marathon",
    "Budget Buddy",
    "Pet Translator",
    "Starship Status",
    "Eco Explorer",
    "Puzzle Palace",
    "Comic Creator",
    "Traffic Tamer",
    "Sleepy Town",
    "Art Auction",
    "History Hunt",
    "Farm Fresh",
    "Game Night",
    "Charity Chain",
    "Travel Tales",
    "Habit Harbor",
    "Quiz Cabin",
    "Local Legends",
    "Calm Corner",
    "Tool Library",
    "Shoe Stylist",
    "Festival Finder",
    "Coding Café",
    "Community Garden"
];

export const descriptions = [
    "A funny app that helps cats review films.",
    "An app where dragons manage their treasure.",
    "A delivery app set during a zombie apocalypse.",
    "A quest-style app for learning coding skills.",
    "A tracker for favourite snacks and ratings.",
    "A marketplace where aliens trade weird objects.",
    "An app that helps plants diagnose their mysterious problems.",
    "A dashboard that predicts weather across different planets.",
    "A recipe book filled with magical meals and potions.",
    "A planner for organising every important puppy adventure.",
    "An app for writing messages that will be opened in the future.",
    "A community platform for planning local beach cleanups.",
    "A leaderboard for competitive robots and their racing times.",
    "A cosy app for discovering books and sharing recommendations.",
    "A private journal for recording dreams seen under moonlight.",
    "An interactive map that helps users solve neighbourhood mysteries.",
    "A gardening assistant that suggests what to plant each season.",
    "A digital canvas for creating and sharing pixel art.",
    "A treasure-hunting game with clues, maps, and hidden rewards.",
    "A browser music studio for mixing loops into original tracks.",
    "A meal-planning app that delivers recipes from the clouds.",
    "A virtual museum where users can learn about dinosaurs.",
    "A fitness game where daily exercise grows a colourful forest.",
    "A playful weather app powered by a team of tiny wizards.",
    "A recipe organiser that launches meal ideas like rockets.",
    "A language-learning app that lights up with every new word.",
    "A challenge tracker for watching classic films with friends.",
    "A simple budget planner for saving toward personal goals.",
    "A playful translator that guesses what pets are trying to say.",
    "A control panel for monitoring a spaceship's daily systems.",
    "A guide for finding sustainable activities and green spaces.",
    "A collection of logic puzzles with unlockable palace rooms.",
    "A tool for designing short comics with characters and panels.",
    "An app that helps commuters find calmer and faster routes.",
    "A town simulation where residents improve their sleep routines.",
    "An online marketplace for buying and bidding on digital art.",
    "A scavenger hunt that brings local history to life.",
    "A service that connects shoppers with nearby farm produce.",
    "A party app for choosing and playing games with friends.",
    "A transparent donation tracker for supporting community projects.",
    "A travel journal for collecting stories, photos, and memories.",
    "A habit tracker where completed goals keep a harbour thriving.",
    "A quiz game set inside a cosy cabin in the mountains.",
    "A guide to interesting people, places, and stories nearby.",
    "A calm space with breathing exercises and relaxing soundscapes.",
    "A borrowing service for sharing tools with local neighbours.",
    "A wardrobe app that suggests outfits for every pair of shoes.",
    "A calendar for discovering concerts, fairs, and local festivals.",
    "A social learning space where developers share coding tips.",
    "A planning tool for coordinating a shared community garden."
];

export const difficulties = [
    "Easy",
    "Medium",
    "Medium",
    "Hard",
    "Easy",
    "Medium",
    "Medium",
    "Hard",
    "Medium",
    "Easy",
    "Medium",
    "Medium",
    "Hard",
    "Easy",
    "Easy",
    "Hard",
    "Medium",
    "Easy",
    "Medium",
    "Hard",
    "Medium",
    "Easy",
    "Medium",
    "Easy",
    "Easy",
    "Medium",
    "Easy",
    "Easy",
    "Hard",
    "Hard",
    "Medium",
    "Medium",
    "Hard",
    "Medium",
    "Medium",
    "Hard",
    "Medium",
    "Easy",
    "Easy",
    "Hard",
    "Medium",
    "Easy",
    "Easy",
    "Medium",
    "Easy",
    "Medium",
    "Easy",
    "Easy",
    "Medium",
    "Medium"
];

export const technologies = [
    "React",
    "React, Firebase",
    "React, Node.js",
    "React, TypeScript",
    "React, LocalStorage",
    "React, MongoDB",
    "React, API integration",
    "React, REST API",
    "React, CSS animations",
    "React, LocalStorage",
    "React, Node.js",
    "React, Firebase",
    "React, Socket.io",
    "React, Firebase",
    "React, LocalStorage",
    "React, Leaflet",
    "React, REST API",
    "React, Canvas API",
    "React, Node.js",
    "React, Web Audio API",
    "React, Express",
    "React, Three.js",
    "React, CSS animations",
    "React, OpenWeather API",
    "React, REST API",
    "React, TypeScript",
    "React, Firebase",
    "React, LocalStorage",
    "React, Web Speech API",
    "React, Node.js",
    "React, Leaflet",
    "React, TypeScript",
    "React, Canvas API",
    "React, Mapbox",
    "React, Node.js",
    "React, Stripe",
    "React, Leaflet",
    "React, Firebase",
    "React, Socket.io",
    "React, Blockchain API",
    "React, Firebase",
    "React, LocalStorage",
    "React, TypeScript",
    "React, REST API",
    "React, Web Audio API",
    "React, Node.js",
    "React, Firebase",
    "React, REST API",
    "React, TypeScript",
    "React, Firebase"
];
